# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry==1.5.1
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        cache: 'poetry' # caching pip dependencies
    - run: poetry install
    - run: poetry run pytest
